# -------------------------
# Database Configuration
# -------------------------
spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA / Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

# -------------------------
# JWT Configuration
# -------------------------
jwt.secret=${JWT_SECRET}
jwt.expiration=3600000

# -------------------------
# Email
# -------------------------
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=${MAIL_USERNAME}
spring.mail.password=${MAIL_PASSWORD}
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

# -------------------------
# Razorpay
# -------------------------
razorpay.key_id=${RAZORPAY_KEY}
razorpay.key_secret=${RAZORPAY_SECRET}


cloudinary.cloud_name=${CLOUD_NAME}
cloudinary.api_key=${CLOUD_API_KEY}
cloudinary.api_secret=${CLOUD_API_SECRET}

app.admin.email=${ADMIN_EMAIL}