# -------------------------
# Database Configuration
# -------------------------
spring.datasource.url=jdbc:postgresql://localhost:5432/test
spring.datasource.username=postgres
spring.datasource.password=root
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA / Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

# -------------------------
# JWT Configuration
# -------------------------
jwt.secret=UNvvcriC5RJutqyznKr3699G8ZmFYOVUZIcnh+vvaPQ=
jwt.expiration=3600000  

# -------------------------
# Email
# -------------------------

spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=tikolesnehal@gmail.com
spring.mail.password=bfpj msgg tmpi xfju
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

# Razorpay API Key
razorpay.key_id=rzp_test_RUUsLf5ulwr2cW
razorpay.key_secret=QxGcGu946jonUyLB9rpeftgh
